name: Manual Salesforce Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          sf version

      - name: Create Auth File
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > auth.txt

      - name: Verify Auth File
        run: |
          ls -l
          wc -c auth.txt
          head -c 20 auth.txt

      - name: Login to Org
        run: |
          sf org login sfdx-url --sfdx-url-file auth.txt --alias targetOrg

      - name: Display Org
        run: |
          sf org display --target-org targetOrg

      - name: Deploy to Salesforce
        run: |
          sf project deploy start --source-dir force-app --target-org targetOrg