name: Manual Salesforce Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g sfdx-cli
          sfdx --version

      - name: Create Auth File
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > auth.txt

      - name: Authenticate Org
        run: |
          sfdx auth:sfdxurl:store -f auth.txt -a targetOrg

      - name: Verify Org
        run: |
          sfdx force:org:display -u targetOrg

      - name: Deploy to Salesforce
        run: |
          sfdx force:source:deploy -p force-app -u targetOrg